app:
    resource: '@AppBundle/Controller/'
    type: annotation
api_backend:
    resource: "@AppBundle/Resources/config/routes.yml"
    type: rest
    prefix: /api
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
