# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    AppBundle\DataFixtures\UserFixtures:
        tags: [doctrine.fixture.orm]
        autowire: true

    AppBundle\DataFixtures\ProductFixtures:
        tags: [doctrine.fixture.orm]
        autowire: true
